FROM golang:1.24 AS build
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o /bin/gateway ./gateway

FROM gcr.io/distroless/base-debian12
COPY --from=build /bin/gateway /gateway
EXPOSE 8080
ENV GRPC_ADDR=user-service:50051
ENTRYPOINT ["/gateway"]