version: "3.9"
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"

  profile-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      - GRPC_ADDR=user-service:50051
    depends_on:
      - user-service